package by.it.selvanovich.news.controller;

public enum CommandName {
    GO_TO_BASE_PAGE, GO_TO_REGISTRATION_PAGE,
    GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS,
    GO_TO_UPDATE_NEWS, GO_TO_ADD_NEWS,
    DO_SIGN_IN, DO_SIGN_OUT, DO_REGISTRATION,
    DO_ADD_NEWS, DO_UPDATE_NEWS,
    DO_DELETE_NEWS
}